# Basic Camera Display Demo. Verify reference of OpenCV libraries in Windows

licenses(["notice"])

package(default_visibility = ["//mediapipe/examples:__subpackages__"])

cc_binary(
    name = "DisplayCamera",
    srcs = ["camera_display.cc"],
    deps = [
        "@windows_opencv//:opencv",
    ],
)

