licenses(["notice"])

package(default_visibility = ["//mediapipe/examples:__subpackages__"])

cc_binary(
    name = "HelloSDL2",
    srcs = ["HelloSDL2.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "@linux_SDL2//:libSDL2",
    ],
)
