/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_gdcccn_vrmeds_kinect_KinectCommunicator */

#ifndef _Included_com_gdcccn_vrmeds_kinect_KinectCommunicator
#define _Included_com_gdcccn_vrmeds_kinect_KinectCommunicator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gdcccn_vrmeds_kinect_KinectCommunicator
 * Method:    initializeKinect
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_gdcccn_vrmeds_kinect_KinectCommunicator_initializeKinect
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_gdcccn_vrmeds_kinect_KinectCommunicator
 * Method:    openKinectSocketClient
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_gdcccn_vrmeds_kinect_KinectCommunicator_openKinectSocketClient
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_gdcccn_vrmeds_kinect_KinectCommunicator
 * Method:    detectKinectSensorFloorAngle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gdcccn_vrmeds_kinect_KinectCommunicator_detectKinectSensorFloorAngle
  (JNIEnv *, jobject);

/*
 * Class:     com_gdcccn_vrmeds_kinect_KinectCommunicator
 * Method:    getBodyJoints
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gdcccn_vrmeds_kinect_KinectCommunicator_getBodyJoints
  (JNIEnv *, jobject);

/*
 * Class:     com_gdcccn_vrmeds_kinect_KinectCommunicator
 * Method:    getBodyJointsOrientations
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gdcccn_vrmeds_kinect_KinectCommunicator_getBodyJointsOrientations
  (JNIEnv *, jobject);

/*
 * Class:     com_gdcccn_vrmeds_kinect_KinectCommunicator
 * Method:    getLatestBodyJoints
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gdcccn_vrmeds_kinect_KinectCommunicator_getLatestBodyJoints
  (JNIEnv *, jobject);

/*
 * Class:     com_gdcccn_vrmeds_kinect_KinectCommunicator
 * Method:    getMergedBodyData
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gdcccn_vrmeds_kinect_KinectCommunicator_getMergedBodyData
(JNIEnv *, jobject);

/*
 * Class:     com_gdcccn_vrmeds_kinect_KinectCommunicator
 * Method:    stopOutput
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gdcccn_vrmeds_kinect_KinectCommunicator_stopOutput
  (JNIEnv *, jobject);

/*
 * Class:     com_gdcccn_vrmeds_kinect_KinectCommunicator
 * Method:    closeKinectSocket
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gdcccn_vrmeds_kinect_KinectCommunicator_closeKinectSocket
  (JNIEnv *, jobject);

/*
 * Class:     com_gdcccn_vrmeds_kinect_KinectCommunicator
 * Method:    shutdownKinect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gdcccn_vrmeds_kinect_KinectCommunicator_shutdownKinect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
